### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by PrivateGER** [PrivateGER/patreon-dl#1]
Currently, the DownloadWorker() function has a few issues, such as converting errors into strings.

Change the [function ](https://github.com/PrivateGER/patreon-dl/blob/553d028b11a5ed207892d7992abffb50d449ec66/DownloadManager.go#L55) and channel handling to restore proper error messages,

**Comment by Rini-Tikki** [comment]
Can I take this issue?

**Comment by Rini-Tikki** [comment]
Opened a PR for this. Please review and merge.
