### ISSUE TITLE
Not working on specific Patreon accounts

### ISSUE THREAD

**Issue by KevlarCaviar** [PrivateGER/patreon-dl#11]
For some reason this is an issue that's only happening on specific Patreon accounts; it'll get stuck on "Promise { <state>: "pending" }" and then spit out a "Error: Promised response from onMessage listener went out of scope" at me after a few seconds, and then the following:
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON datadebugger eval code line 1 > eval:99:13
    <anonymous> debugger eval code line 1 > eval:99
    AsyncFunctionThrow self-hosted:642
    (Async: async)
    <anonymous> debugger eval code line 1 > eval:100
    <anonymous> debugger eval code:1
    AsyncFunctionNext self-hosted:638
    (Async: async)
    <anonymous> debugger eval code:1
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:243
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:167
    evaluateJS resource://devtools/server/actors/webconsole.js:1115
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:1007
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103

**Comment by PrivateGER** [comment]
Could you take a screenshot of the network activity from starting the stager until the crash? The information here isn't sufficient to reproduce the issue.

**Comment by KevlarCaviar** [comment]
<img width="1920" alt="patreon-dl network activity crashing" src="https://user-images.githubusercontent.com/106205344/170299947-a363b250-87a4-47c8-9424-969f64f5c45e.PNG">

Hope this is what you meant. It stops at the last GET.

**Comment by PrivateGER** [comment]
Thank you, that does help. Looks like an interesting bug... could you send me a list of accounts that this happens on? If you don't want it public, you can send an email to privateger@privateger.me.

**Comment by KevlarCaviar** [comment]
My dignity has been gone for a while now, so I'll just list them here.
Tested it on these ones and got the same bug (NSFW so view at your own risk):
Lapin Beau
Dead End Draws
Incognitymous
AfroBull
GreatM8
EGG SHOPPE

Tested it on a SFW account (Kris Straub) and weirdly it worked, but for some reason the images folder didn't appear like it's supposed to.

**Comment by KevlarCaviar** [comment]
Same issues happen with the test build. Strange that the issue was only able to be reproduced on your end with one of the accounts, this seems to be a very inconsistent problem for some reason.

**Comment by PrivateGER** [comment]
Very odd... :/
Until someone else chimes in with more info, this will sadly be a wontfix. It sounds like an issue with Patreon itself.
