### ISSUE TITLE
Capability to download videos? 

### ISSUE THREAD

**Issue by Eiion** [PrivateGER/patreon-dl#12]
Is your nifty little tool able to download videos as well or is it exclusively for pictures?
(I'm considering to subscribe to a creator for one of two of his videos specifically containing information about EQ modification. Since details can easily be forgotten after years I'd like to create a private copy of the videos so I can re-watch them whenever needed to make further adjustments.)

**Comment by PrivateGER** [comment]
Hey. :)

I actually have not tested video downloads. If you do try this, please tell me the result. 
If it doesn't work, you can use [gallery-dl](https://github.com/mikf/gallery-dl). It's a bit more setup, but overall a "larger" project than patreon-dl is.
