### ISSUE TITLE
Small typo in JS snippet

### ISSUE THREAD

**Issue by toertchn** [PrivateGER/patreon-dl#14]
Hello, 
first run shows:

...and run it with ENTER:
(async()=>{eval(await(await **fetch("http**://localhost:9849/gadget")).text());})();

... after finish there comes another snippet which doesn't work. One \\ too much in it

You can download another set of images using the below JS snippet or exit patreon-dl:
(async()=>{eval(await(await **fetch(\\"http**://localhost:9849/gadget\")).text());})();

**Comment by PrivateGER** [comment]
Oh, that's a leftover from some older code. 

Thanks for the report, fixed in 95c3ac3 and will be put into the next release.
