### ISSUE TITLE
How do you run on Mac?

### ISSUE THREAD

**Issue by j-ktz** [PrivateGER/patreon-dl#4]
I've downloaded all the "Mac" apps, but none of them open when you double click?

**Comment by PrivateGER** [comment]
I'll close this one for now, tell me if you had any further issues.

**Comment by maxyjaxy** [comment]
Yeah, I don't think this is working for Mac. I tried to drag both files into terminal but it says access denied. Which of the two files is the one we are supposed to use? Thanks
