### ISSUE TITLE
I paste the string of code from patreon-dl and get this error

### ISSUE THREAD

**Issue by JMorris113** [PrivateGER/patreon-dl#8]
VM169:54 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'split')
    at eval (eval at <anonymous> (posts:1), <anonymous>:54:78) 

sorry if this is a common fix and i failed to understand it I'm new to this.

**Comment by PrivateGER** [comment]
That looks like a bug. What account did you run this on?

**Comment by JMorris113** [comment]
Asyrie

**Comment by Site3op** [comment]
Same error here.

**Comment by Zaneaby** [comment]
Same error here. Its in the for loop that adds the file to downloads, you'll want to check for falsy in parsedInital.included[i].attributes.file_name before splitting it and calling addFileDownload.

**Comment by PrivateGER** [comment]
@Zaneaby Good call. I'll get a new release on when I get the opportunity to do so.

**Comment by PrivateGER** [comment]
A new release has been published, it should fix this issue.
